### ISSUE TITLE
Flaky test observatory

### ISSUE THREAD

**Issue by asaaki** [mimicry-tech/mimicry#34]
I forgot to capture the first times, but I'd like us to keep track of them to see if they are always the same or random.

- PR: https://github.com/mimicry-tech/mimicry/issues/33#issuecomment-891698371
  test: https://github.com/mimicry-tech/mimicry/blob/0380f4b662a64937e5cb3c3cbdc28ea7299763ce/test/mimicry_api/controllers/proxy_controller_test.exs#L16

**Comment by floriank** [comment]
Async testing is hard, I'll try to take a look

**Comment by floriank** [comment]
I have to look for the setup of `inotify-tools` anyway
